### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'git diff XXX --name-only'

### ISSUE THREAD

**Issue by f-liva** [miile7/gitzip#1]
Getting files from diff 2c5cc3617a3a415f38ac53c3a60f62ebffb20003..HEAD
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/fede9/.local/lib/python3.9/site-packages/gitzip/__main__.py", line 4, in <module>
    execute()
  File "/home/fede9/.local/lib/python3.9/site-packages/gitzip/gitzip.py", line 81, in execute
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git diff 2c5cc3617a3a415f38ac53c3a60f62ebffb20003 --name-only'

**Comment by miile7** [comment]
Thank you very much for contributing. Can you please provide the call signature, that would help me a lot.
