### ISSUE TITLE
Getting an error when I execute the command

### ISSUE THREAD

**Issue by UnifySoftTech** [miile7/gitzip#2]
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\gitzip\__main__.py", line 4, in <module>
    execute()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\gitzip\gitzip.py", line 81, in execute
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by miile7** [comment]
Looks like python cannot find `git`. Can you execute the `git` command in your normal terminal? Are you using virtual environments for python with some specific settings? Can you provide the full output that happens before the error?
